name: CI

defaults:
  run:
    working-directory: ./app

env:
  DOCKER_HUB_USER_ID: juancamiloclement
  DOCKER_HUB_EMAIL: juancamiloclement@gmail.com
  DOCKER_HUB_PWD: clement25-98

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PWD

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: $DOCKER_HUB_USER_ID/dockerapp-js:latest